### ISSUE TITLE
Terraform warning messages

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#1]
Hello, I wanted to test this (great) project but I found some warnings when executing the command `terraform plan -out plan.out`.

An example is:

> Warning: Quoted references are deprecated

>on website.tf line 47, in resource "google_compute_managed_ssl_certificate" "default":
  47:   provider = "google-beta"

> In this context, references are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted references are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this reference to silence this warning.

Also, can you explain what and how to "collect the necessary information and put it in terraform.tfvars"?

**Comment by hodl-dot-farm** [comment]
Hi!
Thank you very much for raising issues with the project, I will take notes and update the README page with clarifications.

Recent versions of terraforms are displaying warnings, this one is probably an easy fix, where we need to remove the quotes. Pull Requests are welcome, else I will take care of it.

> Also, can you explain what and how to "collect the necessary information and put it in terraform.tfvars"?

First you should run `terraform plan` and it will interactively ask you for every bit of information it needs.

But you don't want to do that every time, so you are better off writing all of this info in `terraform.tfvars`, as long as you make sure never to commit it.

**Comment by denver-s** [comment]
I am not super familiar with GitHub, but I tried to push a PR but it seems that I don't have the access rights to do it.

> ERROR: Permission to hodl-dot-farm/tezos-on-gke.git denied to denver-s.
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights and the repository exists.
