### ISSUE TITLE
Is tezos-public-node-with-probes in prod?

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#10]
Is [this commit](https://github.com/hodl-dot-farm/tezos-on-gke/commit/81b204e1fa59d81def49815751f27cb360d286b6) supposed to substitute "tezos/tezos-public"? Or is it just a dev test?

**Comment by hodl-dot-farm** [comment]
`tezos-public-node-with-probes` is in production. It restarts the node when all of its public connections have disappeared, something I have seen happening.
