### ISSUE TITLE
Unused variable signer_target_random_hostname

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#12]
Is it unused and removable from variables.tf?

**Comment by hodl-dot-farm** [comment]
it is used in cloudflare config. When you set up your remote signers, that is the hostname they hit to set up the ssh tunnel. Are you using physical signers yet ?

**Comment by denver-s** [comment]
Sorry, I did set DNS manually since I do not use Cloudflare (or better, I do not use a website).
