### ISSUE TITLE
Pod restarting but "/dev/termination-log" is empty

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#13]
Hey! Sorry to bother but I've got an issue.

Once a day the pods restart, for no reason apparently. They become inactive for 30 seconds which is `terminationGracePeriodSeconds` but I don't get why.

I checked the YAML and read `terminationMessagePath: /dev/termination-log` and `terminationMessagePolicy: File` but that file is empty.

**Comment by hodl-dot-farm** [comment]
I see the same thing on my setup and suspect a memory leak. I see memory going up continuously and the baking pod restart when the memory usage hits around 2gb.

Do you have access to memory consumption data ? Could you check ?

I see the new version 7.0 fixes a few memory leaks, it may be worth a try, but I have not tried yet so I do not know if it will work out of the box.

http://tezos.gitlab.io/releases/version-7.html

**Comment by denver-s** [comment]
I was thinking about the same as you about version 7 memory leaks fixes. Let’s wait for a stable version and see if it’s solved.

**Comment by hodl-dot-farm** [comment]
You may also want to check if your vms are preemptible. By default, they are:
https://github.com/hodl-dot-farm/tezos-on-gke/blob/master/terraform/gcp.tf#L298

Preemptible vms will restart once a day, and in gke it causes containers to restart without increasing the restart count, which is a bit confusing.

**Comment by denver-s** [comment]
It might be better to not use preemptible VMs for the private node?

**Comment by hodl-dot-farm** [comment]
That's possible. Recently I have been missing a few endorsements, I suspect preemtible vms are to blame. I just switched to full-price vms and I will be monitoring.

**Comment by denver-s** [comment]
> Preemptible vms will restart once a day, and in gke it causes containers to restart without increasing the restart count, which is a bit confusing.

After setting the VMs to be non-preemptible, the issue seems to be fixed as expected. Can confirm @hodl-dot-farm ?

**Comment by hodl-dot-farm** [comment]
yes, fixed for me too
