### ISSUE TITLE
archive_url vs snapshot_url, what's the difference?

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#2]
archive_url is described as "The public URL where to download the full historical tezos blockchain for quicker sync of the private node".

Using TezosShots, is this URL (mainnet full mode) ok?
https://tezosshots.com/download/461/

And what about snapshot_url ("The public URL where to download the tezos blockchain snapshot for quicker sync of the public nodes")? Rolling mode?

**Comment by hodl-dot-farm** [comment]
This is what I used:

```archive_url="http://quicksync.chainlayer.io/tezos/tezos.mainnet.20190921.2324.archive.tar.lz4"```

Please let me know if the tezosshots url worked.

The snapshot_url should point to a full snapshot, but you may swap this line with the comment https://github.com/hodl-dot-farm/tezos-on-gke/blob/master/tezos-baker/tezos-public-node-stateful-set.yaml#L53-L54
and then it may work with a rolling snaphsot. When I tried, it didn't work, but you may have better luck.
