### ISSUE TITLE
What is website_archive?

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#6]
Is it https://github.com/hodl-dot-farm/hodl-farm-tezos-website?

**Comment by hodl-dot-farm** [comment]
Almost, for hodl.farm it's https://github.com/hodl-dot-farm/hodl-farm-tezos-website/archive/master.zip

If you want a website, you should create a jekyll source repository and provide the link to it.

**Comment by denver-s** [comment]
That's what I thought. Might be better to provide that link in the documentation.
